### ISSUE TITLE
Error accessing the accellerometer on Linux and windows

### ISSUE THREAD

**Issue by ingegno** [Fri3dCamp/Fri3dBadge#9] opened 2018-08-19 19:17 UTC
Tested with Linux Ubuntu 18.04 and Windows 10, Arduino 1.8.5
Compilation and upload works, but when 

    #include <Fri3dAccelerometer.h>

is included, the code never reaches setup(). 
Code without this seems to work fine. Upload afterwards with different code is still possible, so uploading keeps working.

**Comment by calmera** [comment] 2018-08-20 09:23
we have the impression that the accelero lib tries to directly write code into the memory of the ESP, which happens to overwrite the bootloader. Flashing with the bootloader solves the flashing issues, but it still renders the accelerometer unusable

**Comment by nvdbleek** [comment] 2018-08-20 19:39
@calmera which version of Arduino studio and additional boards manage URL are you using which works? I can try to install the same version and check if that perhaps solves the problem.

**Comment by nvdbleek** [comment] 2018-08-21 19:54
The issue also occurs on my Mac with Arduino 1.8.5 and https://dl.espressif.com/dl/package_esp32_index.json

**Comment by jantje** [comment] 2018-08-21 20:04
>we have the impression that the accelero lib tries to directly write code into the memory of the ESP, 

Simply including a header file should not result in any code being activated.
Actually as the library is included in the ketch, the Fri3dAccelerometer.cpp is compiled and as such Fri3dAccelerometer.h is part of all sketches build with the Fri3dBadge lib.

My first suspicion is that the Fri3dAccelerometer.h redefines something which is used in your code (for which arduino IDE does not give a warning).

**Comment by arnevandenberghe** [comment] 2018-08-23 08:55
Just out of curiosity: how come this is not an issue in the firmware that was on the badge when camp started? 
What's the difference between the compiled binary under `bin/defaultFirmware` and the sketch under `Fri3dBadge/examples/2.Demos/defaultFirmware/`?

**Comment by aliekens** [comment] 2018-08-23 11:32
Can someone with this issue check whether they have also installed the Adafruit ADXL345 library, next to the Fri3d Camp badge library? We have included this library for simplicity for our users, but maybe this clashes with other installed libraries.

**Comment by nvdbleek** [comment] 2018-08-23 13:37
@aliekens I didn't install Adafruit_ADXL345 myself (just did a default install, added https://dl.espressif.com/dl/package_esp32_index.json, installed the esp32 library and finally downloaded Fri3dBadge as a zip and added the zip). But it is installed in my Arduino studio. Should I uninstall Adafruit_ADXL345? And re-try uploading the sketch?

**Comment by arnevandenberghe** [comment] 2018-08-23 13:45
Same thing here. I installed Arduino studio on camp and only followed the README instructions. No extra libraries.

**Comment by ingegno** [comment] 2018-08-23 14:40
I did not have Adafruit_ADXL345 installed and had this issue. During Fri3d I installed ADXL345, and issue remained. Off course, it could be we need to remove the one installed with the badge ...

**Comment by driesderoeck** [comment] 2018-08-23 19:21
Confirmed issue here, arduino IDE 1.8.6 without the Adafruit_ADXL345 installed. (OSX 10.13.6)

**Comment by driesderoeck** [comment] 2018-08-23 22:28
Just checked (briefly) with @aliekens over chat, it seems that the default 'sensortest' Adafruit_ADXL345 library example works out of the box (https://github.com/adafruit/Adafruit_ADXL345). But that exact library ported to the fri3dbadge does not.
But I guess it's good news that the ADXL lib works out of the box ... I'll do some more work tomorrow trying to mess around with Fri3dbadge examples starting from the ADXL lib. (perhaps I'll run into the issue that way...)

**Comment by driesderoeck** [comment] 2018-08-23 22:53
I can also add that flashing the badge using flash.sh script in the tarball works to get the badge back to its original 'state' (https://github.com/Fri3dCamp/Fri3dBadge/blob/master/fri3d_default_firmware.tgz). Accelerometer seems to work fine in that case.

**Comment by bgey** [comment] 2018-08-24 17:12
Additional comment: the example code "1. Basics / accelerometer" doesn't produce any output. Removing all code except the normal Serial.print commando's works. Once I initialize Fri3dAccelerometer, no output is reaching the serial monitor anymore.  ( Fri3dAccelerometer accel = Fri3dAccelerometer(); )

**Comment by driesderoeck** [comment] 2018-08-24 22:28
Probably pinned the issue down to the way setup() is handled in the Arduino environment. The Fri3dAccelerometer library attempts to initiate the accelerometer outside of the Arduino setup() - which seems to be causing issues on some installs. @aliekens has a fix ready, should be up shortly.

**Comment by aliekens** [comment] 2018-08-24 22:57
We have finally found the issue! In some Arduino IDE installs, we have to init the accelerometer in the setup function, not before it, which, oddly enough, does work in other Arduino environments. We have not found why, but we have a fix:

We have now introduced a `Fri3dAccelerometer::begin()` that you have to call as `accel.begin()` from your `setup()` to initialize the accelerometer. The library and examples have been updated in commit https://github.com/Fri3dCamp/Fri3dBadge/commit/c42d44a7dff1480b7f56af79f2de1362a225f8dd

Please pull the updates, this issue can now be closed! Thanks to all for reporting and finding a fix for this issue.

**Closed as completed by aliekens** 2018-08-24 22:57 UTC

**Comment by jantje** [comment] 2018-08-25 08:53
good work :-) thanks
